name: pre-commit

on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull-request:
    branches:
      - 'main'
      - 'release/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Install Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"

    - name: Run pre-commit
      uses: pre-commit/action@v4.6.2
